# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.URLField()),
                ('qr_code', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
